BOT_NAME = 'Intelligence'

SPIDER_MODULES = ['Intelligence.spiders']
NEWSPIDER_MODULE = 'Intelligence.spiders'

MONGODB_SERVER = "localhost"
MONGODB_PORT = 27017
MONGODB_DB = "intelligence"
MONGODB_COLLECTION_TEMP_TRACK = "temp_track"
MONGODB_COLLECTION_TRACK = "track"

GOOGLE_EMAIL = 'oleksandr.hubachov@gmail.com'
GOOGLE_PASSWORD = 'austral1a'
GOOGLE_SPREADSHEET_KEY = '1dY9oDnedF06jWdRq3wnM5-Ce5TYivWXK7VR7SyKl2Bg'
GOOGLE_SPREADSHEET_KEY0 = '15KI_NCnoDsNPdUJtQbiy79rdVsMb_5Du6IdqNFdZLnM'
GOOGLE_WORKSHEET_ID = 'od6'